# netlify.toml
[build]
  command   = "npm run build"
  publish   = "dist/public"                 # Vite outputs to /dist by default
  functions = "netlify/functions"

[functions]
  node_bundler   = "esbuild"
  included_files = [".env"]          # available to all functions

# Make sure both functions can bundle node deps
[functions."sendAuditPdf"]
  external_node_modules = ["pdf-lib", "nodemailer", "dotenv"]

[functions."sendFeedbackEmail"]
  external_node_modules = ["pdf-lib", "nodemailer", "dotenv"]

[dev]
  command   = "npm run dev"
  framework = "vite"
  targetPort = 5173
  port       = 8888

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy              = "strict-origin-when-cross-origin"
    Strict-Transport-Security    = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options       = "nosniff"
    X-Frame-Options              = "DENY"
    X-XSS-Protection             = "1; mode=block"
