[build]
  command = "node netlify-build-transform.cjs 'NODE_ENV=production node build-netlify.cjs'"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SESSION_SECRET = "chaiiwala-dashboard-secure-session-key"
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions/api"
  VITE_API_URL = "/.netlify/functions/api"

[dev]
  framework = "#custom"
  port = 8888
  publish = "dist/public"
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'self'; font-src * 'self' https://fonts.gstatic.com; style-src * 'self' https://fonts.googleapis.com 'unsafe-inline'; script-src * 'self' 'unsafe-eval' 'unsafe-inline'; img-src * 'self' data: blob:; connect-src * 'self' https://fonts.googleapis.com https://*.netlify.app https://*.netlify.com https://*.chaiiwala.co.uk"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
