[build]
  command = "node netlify-build-transform.js node build-netlify.js"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SESSION_SECRET = "chaiiwala-dashboard-secure-session-key"
  NODE_ENV = "production"

[dev]
  framework = "#custom"
  port = 8888
  publish = "dist/public"
  autoLaunch = false

# Content Security Policy headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://*.netlify.app https://*.netlify.com; font-src 'self' https://fonts.gstatic.com data:; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.netlify.app https://*.netlify.com; img-src 'self' data: blob:; connect-src 'self' https://*.netlify.app https://*.netlify.com; worker-src 'self' blob:; frame-src 'self'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
