[build]
  command = "npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SESSION_SECRET = "chaiiwala-dashboard-secure-session-key"

[dev]
  framework = "#custom"
  port = 8888
  publish = "dist/public"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Common secure headers for ALL builds
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

# Development (deploy-preview and branch-deploy) relaxed CSP
[context.deploy-preview]
  [[headers]]
    for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self' data: blob: *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; connect-src 'self' *; img-src 'self' data: blob: *; frame-src *; style-src 'self' 'unsafe-inline' *"

[context.branch-deploy]
  [[headers]]
    for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self' data: blob: *; script-src 'self' 'unsafe-inline' 'unsafe-eval' *; connect-src 'self' *; img-src 'self' data: blob: *; frame-src *; style-src 'self' 'unsafe-inline' *"

# Production secure CSP
[context.production]
  [[headers]]
    for = "/*"
    [headers.values]
      Content-Security-Policy = "default-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data:; frame-src 'self'; style-src 'self';"
