[build]
  command = "npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SESSION_SECRET = "chaiiwala-dashboard-secure-session-key"

[dev]
  framework = "#custom"
  port = 8888
  publish = "dist/public"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers including CSP with 'unsafe-eval' to allow JavaScript eval functionality
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data:; connect-src 'self' *.netlify.app"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
