[build]
command = "npx vite build"
publish = "dist/public"
functions = "netlify/functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"