[build]
  command = "npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  NODE_VERSION = "18.19.0"
  SESSION_SECRET = "chaiiwala-dashboard-secure-session-key"

[dev]
  framework = "#custom"
  port = 8888
  publish = "dist/public"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers including CSP with 'unsafe-eval' to allow JavaScript eval functionality
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
