[build]
command = "npm run build"        # You can still run `npx vite build` manually if needed
publish = "dist"
functions = "netlify/functions"
framework = "vite"               # Avoids the "Invalid framework" warning

[functions]
node_bundler = "esbuild"
included_files = [".env"]        # Applies to all functions

[functions."sendFeedbackEmail"]
node_bundler = "esbuild"
included_files = [".env"]
external_node_modules = ["pdf-lib", "nodemailer", "dotenv"]
js_external_modules = true

[dev]
framework = "vite"               # ✅ Correct value
command = "npm run dev"
targetPort = 5173
port = 8888

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
